spring:
  application:
    name: market-service
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: 8081
  shutdown: graceful

grpc:
  server:
    port: 9090
    enableKeepAlive: true
    keepAliveTime: 30s
    keepAliveTimeout: 10s
    permitKeepAliveWithoutCalls: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
    webclient:
      enabled: true

market:
  price-interval-ms: 12000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

