spring.application.name=simulation-service
server.port=8084
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

grpc.client.market-service.address=discovery:///market-service
grpc.client.market-service.negotiationType=PLAINTEXT
grpc.client.market-service.keepAliveTime=30s
grpc.client.market-service.keepAliveTimeout=10s
grpc.client.market-service.keepAliveWithoutCalls=true
grpc.client.market-service.enableRetry=true
grpc.client.market-service.maxRetryAttempts=3

grpc.client.strategy-service.address=discovery:///strategy-service
grpc.client.strategy-service.negotiationType=PLAINTEXT
grpc.client.strategy-service.keepAliveTime=30s
grpc.client.strategy-service.keepAliveTimeout=10s
grpc.client.strategy-service.keepAliveWithoutCalls=true

grpc.client.portfolio-service.address=discovery:///portfolio-service
grpc.client.portfolio-service.negotiationType=PLAINTEXT
grpc.client.portfolio-service.keepAliveTime=30s
grpc.client.portfolio-service.keepAliveTimeout=10s
grpc.client.portfolio-service.keepAliveWithoutCalls=true

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s
