spring:
  application:
    name: discovery-server

  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  port: 8761
  shutdown: graceful

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
