spring.application.name=portfolio-service
server.port=8083

grpc.server.port=9092
grpc.server.enableKeepAlive=true
grpc.server.keepAliveTime=30s
grpc.server.keepAliveTimeout=10s
grpc.server.permitKeepAliveWithoutCalls=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.webclient.enabled=true

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
